# Generated by Django 4.2.17 on 2025-01-03 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='children',
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='filemanager.folder'),
        ),
    ]
