# Generated by Django 4.2.17 on 2025-01-04 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0003_remove_folder_children_folder_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='filemanager.folder')),
            ],
        ),
    ]
